### ISSUE TITLE
Visibility control is documented as necessary for the user to include

### ISSUE THREAD

**Issue by tfoote** [tfoote/rosidl_typesupport_protobuf#12]
[I noticed](https://github.com/tfoote/rosidl_typesupport_protobuf/pull/9/files#r1427333856) that the visibility control was added into the documentation. I'd like to double check that this is either:

1) Not necessary and we can remove it from the documentation
2) If it is necessary add it to the generated header files in the appropriate places so that it becomes not necessary and then remove it from the documentation.

**Comment by tfoote** [comment]
Also potentially clean up type declaration that might not be necessary: https://github.com/tfoote/rosidl_typesupport_protobuf/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R27

**Comment by gdiaz-guevara** [comment]
In this [branch](https://github.com/tfoote/rosidl_typesupport_protobuf/tree/protobuf_imports), I added the generated header file in the appropriate places and also removed it from the documentation.

Also, I cleaned up the documentation and removed the type declaration that is not necessary.
