### ISSUE TITLE
Create upstream PR for moving forward past foxy to rolling compatible

### ISSUE THREAD

**Issue by tfoote** [tfoote/rosidl_typesupport_protobuf#5]

**Comment by gonzodepedro** [comment]
Branch: https://github.com/tfoote/rosidl_typesupport_protobuf/tree/update-to-current

**Comment by tfoote** [comment]
Trying out on the ROS 2 CI [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19944)](http://ci.ros2.org/job/ci_linux/19944/)

**Comment by tfoote** [comment]
https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/pull/26
